name: 'Revision contexto de commits'
description: 'Revision para distintos commits'
inputs:
  account-id:  # NewRelic Accoun ID
    description: 'Prueba'
    required: true
runs:
  using: 'node16'
  main: 'index.js'